USE spacex_cloud;

CREATE TABLE IF NOT EXISTS repos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  name VARCHAR(120) NOT NULL,
  default_branch VARCHAR(60) NOT NULL DEFAULT 'main',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS repo_commits (
  id INT AUTO_INCREMENT PRIMARY KEY,
  repo_id INT NOT NULL,
  message VARCHAR(255) NOT NULL,
  author VARCHAR(120) NOT NULL,
  sha VARCHAR(12) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (repo_id) REFERENCES repos(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);
